In [ ]:
# program 1: Calculate total weekly energy from a list
Kwh_Used =[100,399,454,667,533,564,600,378,868]
total_energy = sum(Kwh_Used)
print(f"Total Energy used: {total_energy} Kwh")

Total Energy used: 4563 Kwh

In [ ]:
building_usage = {
    "CSE" : 100,
    "HOSTEL" : 399
}
print("CSE used:",building_usage["CSE"],"Kwh")

CSE used: 100 Kwh

In [ ]:
with open("README.md", "w") as file:
    file.write("# Smart Campus Energy Project\n")
    file.write("This repository contains my week 1 hands-on Python and pandas assignment.\n")
print("README.md has been successfully created!")

README.md has been successfully created!

In [ ]:
with open("campus_energy(Sheet1).csv","r") as file:
  for line in file.readlines():
    print(line.strip())

﻿Date,Building,Kwh_Used,Peak_Hour,Usage
26-05-2026,CSE,100,333,
27-05-2026,HOSTEL,399,654,
28-05-2026,ECE,454,324,
29-05-2026,ECE,667,357,
30-05-2026,CIVIL,533,345,
31-05-2026,CSE,564,345,
31-05-2027,HOSTEL,600,533,
31-05-2028,ECE,378,355,
31-05-2029,CSE,868,342,

In [ ]:
import pandas as pd

df = pd.read_csv("campus_energy(Sheet1).csv")

print("Here is the raw data:")
display(df.head())

building_total = df.groupby('Building')['Kwh_Used'].sum()
print("Total energy used by each building:")
print(building_total)

print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         Date Building  Kwh_Used  Peak_Hour  Usage
0  26-05-2026      CSE       100        333    NaN
1  27-05-2026   HOSTEL       399        654    NaN
2  28-05-2026      ECE       454        324    NaN
3  29-05-2026      ECE       667        357    NaN
4  30-05-2026    CIVIL       533        345    NaN

Total energy used by each building:
Building
CIVIL      533
CSE       1532
ECE       1499
HOSTEL     999
Name: Kwh_Used, dtype: int64

Statistical Summary:

         Kwh_Used   Peak_Hour  Usage
count    9.000000    9.000000    0.0
mean   507.000000  398.666667    NaN
std    213.675572  114.968474    NaN
min    100.000000  324.000000    NaN
25%    399.000000  342.000000    NaN
50%    533.000000  345.000000    NaN
75%    600.000000  357.000000    NaN
max    868.000000  654.000000    NaN

In [ ]:
with open("README.md", "w") as file:
  file.write("# Smart campus Energy Project\n")
  file.write("This repository contains my week 1 hands-on- Python and pandas assignment.\n")
print("README.md has been successfully created!")

README.md has been successfully created!